#
# Dockerfile.test
#
# Container that carries all distributedlog folders, and launches the ZooKeeper console by default.
# Useful for running tests, linked to other running services.
#
FROM openjdk:8-jre-alpine
MAINTAINER Asko Kauppi [akauppi@gmail.com]

ARG DL=incubator-distributedlog
ARG VERSION=latest

ARG APP=/app

LABEL name="distributedlog-test" version=$VERSION

# Copy all files
#
COPY $DL $APP

RUN apk add --no-cache bash \
  && true

WORKDIR $APP

# tbd. Wasn't able to bring the $APP to the ENTRYPOINT/CMD parameters
#ENV APP=$APP
CMD [ "/app/distributedlog-service/bin/dlog", "zkshell", "localhost:2181" ]
