version: '2'
services:
  zk-1:
    image: 31z4/zookeeper
    restart: always
    ports:
     - "2181:2181"
    volumes:

  bk-1:
    build: Dockerfile.bk
    ports:
     - "3181:3181"
     - "9001:9001"
    volumes:

  # Q: How to provide 'ID'==1 to these?
  wp-1:
    build: Dockerfile.wp
    ports:
     - "4181:4181"
     - "20001:20001"
    volumes:

#volumes:
#    logs: {}
